import {useCallback,useEffect,useMemo,useState} from 'react'
import './App.css'
import './extra.css'
import {I18nProvider,useI18n} from './i18n.jsx'

const categories=['Barchasi','Elektronika','Kiyim','Uy va bog‘','Sport','Go‘zallik','Kitoblar','Avto']
const catalog=[
 ['Elektronika','Simsiz quloqchin','wireless,headphones'],['Elektronika','Smart soat','smartwatch'],['Elektronika','Mexanik klaviatura','mechanical,keyboard'],['Elektronika','Portativ kolonka','portable,speaker'],['Elektronika','Powerbank','powerbank'],
 ['Kiyim','Premium huddi','hoodie'],['Kiyim','Yengil krossovka','sneakers'],['Kiyim','Denim kurtka','denim,jacket'],['Kiyim','Teri sumka','leather,handbag'],['Kiyim','Klassik ko‘ylak','dress,shirt'],
 ['Uy va bog‘','Aqlli chiroq','table,lamp'],['Uy va bog‘','Robot changyutgich','robot,vacuum'],['Uy va bog‘','Qahva qaynatgich','coffee,maker'],['Uy va bog‘','Oshxona to‘plami','kitchenware'],['Uy va bog‘','Yumshoq kreslo','armchair'],
 ['Sport','Fitness ganteli','dumbbells'],['Sport','Futbol to‘pi','soccer,ball'],['Sport','Yoga gilamchasi','yoga,mat'],['Sport','Sport ryukzagi','sports,backpack'],['Sport','Tennis raketkasi','tennis,racket'],
 ['Go‘zallik','Parfyum','perfume,bottle'],['Go‘zallik','Yuz kremi','face,cream'],['Go‘zallik','Soch feni','hair,dryer'],['Go‘zallik','Kosmetika sumkasi','cosmetic,bag'],['Go‘zallik','Manikyur to‘plami','manicure,set'],
 ['Kitoblar','Dasturlash kitobi','programming,book'],['Kitoblar','Biznes kitobi','business,book'],['Kitoblar','Jahon adabiyoti','novel,book'],['Kitoblar','Ingliz tili kitobi','english,textbook'],['Kitoblar','Dizayn kitobi','design,book'],
 ['Avto','Video registrator','dash,camera'],['Avto','Telefon ushlagich','car,phone,holder'],['Avto','Avto changyutgich','car,vacuum'],['Avto','Asboblar to‘plami','car,toolkit'],['Avto','Avto kompressor','car,compressor']
]
const fallback={Elektronika:'/products/electronics.png',Kiyim:'/products/fashion.png','Uy va bog‘':'/products/home.png',Sport:'/products/sport.png','Go‘zallik':'/products/beauty.png',Kitoblar:'/products/books.png',Avto:'/products/auto.png'}
const initialProducts=Array.from({length:1000},(_,i)=>{const [category,base,term]=catalog[i%catalog.length];return{id:i+1,name:base+' '+String.fromCharCode(65+i%6)+(Math.floor(i/catalog.length)+1),category,price:49000+(i*7919)%4950000,old:i%3===0?89000+(i*8941)%5300000:0,rating:(4.1+i%9/10).toFixed(1),reviews:12+i*17%870,stock:5+i*13%95,seller:'Ubaydulloh',sellerId:'admin',image:`https://loremflickr.com/600/480/${term}?lock=${i+1}`,fallback:fallback[category]}})
const money=n=>new Intl.NumberFormat('uz-UZ').format(n)+' so‘m'
const savedArray=key=>{try{const value=JSON.parse(localStorage.getItem(key)||'[]');return Array.isArray(value)?value:[]}catch{return []}}

const copy={
 uz:{search:'Mahsulotlarni qidiring...',catalog:'Katalog',favorites:'Sevimli',cart:'Savatcha',profile:'Profil',hero:'Kerakli narsani oson toping.',heroText:'1000 dan ortiq mahsulot, ishonchli sotuvchilar va tezkor yetkazib berish.',start:'Xaridni boshlash',popular:'Ommabop mahsulotlar',all:'Barchasi',products:'mahsulot',add:'Savatchaga qo‘shish',reviews:'sharh'},
 ru:{search:'Поиск товаров...',catalog:'Каталог',favorites:'Избранное',cart:'Корзина',profile:'Профиль',hero:'Найдите всё, что вам нужно.',heroText:'Более 1000 товаров, надежные продавцы и быстрая доставка.',start:'Начать покупки',popular:'Популярные товары',all:'Все',products:'товаров',add:'Добавить в корзину',reviews:'отзывов'},
 en:{search:'Search products...',catalog:'Catalog',favorites:'Favorites',cart:'Cart',profile:'Profile',hero:'Find everything you need.',heroText:'Over 1000 products, trusted sellers and fast delivery.',start:'Start shopping',popular:'Popular products',all:'All',products:'products',add:'Add to cart',reviews:'reviews'}
}
const categoryI18n={Elektronika:{ru:'Электроника',en:'Electronics'},Kiyim:{ru:'Одежда',en:'Fashion'},'Uy va bog‘':{ru:'Дом и сад',en:'Home & garden'},Sport:{ru:'Спорт',en:'Sports'},'Go‘zallik':{ru:'Красота',en:'Beauty'},Kitoblar:{ru:'Книги',en:'Books'},Avto:{ru:'Авто',en:'Automotive'},Barchasi:{ru:'Все',en:'All'}}
const productI18n={
 'Simsiz quloqchin':['Беспроводные наушники','Wireless headphones'],'Smart soat':['Умные часы','Smart watch'],'Mexanik klaviatura':['Механическая клавиатура','Mechanical keyboard'],'Portativ kolonka':['Портативная колонка','Portable speaker'],Powerbank:['Повербанк','Power bank'],
 'Premium huddi':['Премиум худи','Premium hoodie'],'Yengil krossovka':['Лёгкие кроссовки','Lightweight sneakers'],'Denim kurtka':['Джинсовая куртка','Denim jacket'],'Teri sumka':['Кожаная сумка','Leather bag'],'Klassik ko‘ylak':['Классическая рубашка','Classic shirt'],
 'Aqlli chiroq':['Умная лампа','Smart lamp'],'Robot changyutgich':['Робот-пылесос','Robot vacuum'],'Qahva qaynatgich':['Кофеварка','Coffee maker'],'Oshxona to‘plami':['Кухонный набор','Kitchen set'],'Yumshoq kreslo':['Мягкое кресло','Soft armchair'],
 'Fitness ganteli':['Фитнес-гантели','Fitness dumbbells'],'Futbol to‘pi':['Футбольный мяч','Football'],'Yoga gilamchasi':['Коврик для йоги','Yoga mat'],'Sport ryukzagi':['Спортивный рюкзак','Sports backpack'],'Tennis raketkasi':['Теннисная ракетка','Tennis racket'],
 Parfyum:['Парфюм','Perfume'],'Yuz kremi':['Крем для лица','Face cream'],'Soch feni':['Фен для волос','Hair dryer'],'Kosmetika sumkasi':['Косметичка','Cosmetic bag'],'Manikyur to‘plami':['Маникюрный набор','Manicure set'],
 'Dasturlash kitobi':['Книга по программированию','Programming book'],'Biznes kitobi':['Книга о бизнесе','Business book'],'Jahon adabiyoti':['Мировая литература','World literature'],'Ingliz tili kitobi':['Учебник английского','English textbook'],'Dizayn kitobi':['Книга по дизайну','Design book'],
 'Video registrator':['Видеорегистратор','Dash camera'],'Telefon ushlagich':['Держатель телефона','Phone holder'],'Avto changyutgich':['Автопылесос','Car vacuum'],'Asboblar to‘plami':['Набор инструментов','Tool kit'],'Avto kompressor':['Автокомпрессор','Car compressor']
}
const trCat=(name,lang)=>lang==='uz'?name:categoryI18n[name]?.[lang]||name
const trProduct=(name,lang)=>{if(lang==='uz')return name;const base=Object.keys(productI18n).find(x=>name.startsWith(x));return base?name.replace(base,productI18n[base][lang==='ru'?0:1]):name}

function Logo({light=false}){return <span className={'siteLogo '+(light?'light':'')}><i><b>B</b></i><strong>bozorly<span>.</span></strong></span>}
function DockIcon({name}){
 const paths={
  home:<><path d="M3 10.8 12 3l9 7.8"/><path d="M5.5 9.5V21h13V9.5M9.5 21v-6h5v6"/></>,
  catalog:<><rect x="3" y="3" width="7" height="7" rx="2"/><rect x="14" y="3" width="7" height="7" rx="2"/><rect x="3" y="14" width="7" height="7" rx="2"/><rect x="14" y="14" width="7" height="7" rx="2"/></>,
  chat:<><path d="M20.5 11.5a8.5 8.5 0 0 1-9 8.48 9.8 9.8 0 0 1-3.8-.98L3 20.5l1.55-4.35A8.5 8.5 0 1 1 20.5 11.5Z"/><path d="M8 12h.01M12 12h.01M16 12h.01"/></>,
  cart:<><path d="M3 4h2l2.1 10.1a2 2 0 0 0 2 1.6h7.9a2 2 0 0 0 1.9-1.4L21 7H6"/><circle cx="9" cy="20" r="1"/><circle cx="18" cy="20" r="1"/></>,
  profile:<><circle cx="12" cy="8" r="4"/><path d="M4.5 21a7.5 7.5 0 0 1 15 0"/></>
 }
 return <svg viewBox="0 0 24 24" aria-hidden="true"><g fill="none" stroke="currentColor" strokeWidth="1.9" strokeLinecap="round" strokeLinejoin="round">{paths[name]}</g></svg>
}
function ProductImage({p}){return <img src={p.image} alt={p.name} loading="lazy" onError={e=>{if(p.fallback&&!e.currentTarget.dataset.fallback){e.currentTarget.dataset.fallback='1';e.currentTarget.src=p.fallback}}}/>}

function AuthPage({onAuth}){
 const {t,lang,setLang}=useI18n()
 const [login,setLogin]=useState(true),[form,setForm]=useState({login:'',name:'',email:'',phone:'',password:''}),[error,setError]=useState(''),[loading,setLoading]=useState(false)
 const submit=async e=>{e.preventDefault();setError('');setLoading(true);try{const u=login?await api('/login',{method:'POST',body:JSON.stringify({login:form.login,password:form.password})}):await api('/register',{method:'POST',body:JSON.stringify(form)});onAuth(u)}catch(err){setError(err.message)}finally{setLoading(false)}}
 return <main className="authPage"><section className="authVisual"><Logo light/><div className="authArt"><div className="visualOrb"></div><img src="/products/electronics.png" alt="Marketplace"/><span className="visualBadge one">✓ {t('trustedSellers')}</span><span className="visualBadge two">⚡ {t('fastDelivery')}</span></div><div><h1>{t('authHero')}</h1><p>{t('authHeroText')}</p></div></section><section className="authSide"><form className="authBox" onSubmit={submit}><div className="authTop"><Logo/><label className="languagePicker"><span>{t('language')}</span><select value={lang} onChange={e=>setLang(e.target.value)}><option value="uz">UZ</option><option value="ru">RU</option><option value="en">EN</option></select></label></div><h2>{login?t('welcome'):t('createAccount')}</h2><p>{login?t('loginHint'):t('registerHint')}</p><div className="authSwitch"><button type="button" className={login?'active':''} onClick={()=>setLogin(true)}>{t('login')}</button><button type="button" className={!login?'active':''} onClick={()=>setLogin(false)}>{t('register')}</button></div>{!login&&<><label>{t('fullName')}<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder={t('yourName')}/></label><label>{t('phone')}<input required type="tel" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="+998 90 123 45 67"/></label></>}<label>{t('emailLogin')}<input required value={login?form.login:form.email} onChange={e=>login?setForm({...form,login:e.target.value}):setForm({...form,email:e.target.value})} placeholder={login?'Email yoki Ubaydulloh':'email@example.com'}/></label><label>{t('password')}<input required type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} placeholder="••••••••"/></label>{error&&<div className="formError">{error}</div>}<button disabled={loading} className="primary full">{loading?t('waiting'):login?`${t('enterSystem')} →`:`${t('create')} →`}</button></form></section></main>
}

function Card({p,favs,setFavs,addCart,open,lang}){const liked=favs.includes(p.id),t=copy[lang];return <article className="card"><div className="pic" onClick={()=>open(p)}><ProductImage p={p}/>{p.old>0&&<span className="sale">−15%</span>}<button className={'heart '+(liked?'liked':'')} onClick={e=>{e.stopPropagation();setFavs(liked?favs.filter(x=>x!==p.id):[...favs,p.id])}}>{liked?'♥':'♡'}</button></div><div className="info"><small>{trCat(p.category,lang)}</small><h3 onClick={()=>open(p)}>{trProduct(p.name,lang)}</h3><div className="rating"><b>★ {p.rating}</b> ({p.reviews} {t.reviews})</div><div className="price"><div><strong>{money(p.price)}</strong>{p.old>0&&<del>{money(p.old)}</del>}</div><button aria-label={t.add} onClick={()=>addCart(p)}>＋</button></div></div></article>}


function Store({products,user,lang,setLang,onLogout,onPanel}){
 const {t}=useI18n(),[page,setPage]=useState('home'),[query,setQuery]=useState(''),[cat,setCat]=useState('Barchasi'),[sort,setSort]=useState('popular'),[limit,setLimit]=useState(20),[favs,setFavs]=useState(()=>savedArray('bozor-favs')),[cart,setCart]=useState(()=>savedArray('bozor-cart')),[selected,setSelected]=useState(null),[toast,setToast]=useState('')
 useEffect(()=>{try{localStorage.setItem('bozor-favs',JSON.stringify(favs))}catch{console.warn('Sevimlilar saqlanmadi')}},[favs]);useEffect(()=>{const compact=cart.map(p=>({...p,image:p.image?.startsWith('data:')?p.fallback:p.image}));try{localStorage.removeItem('bozor-cart');localStorage.setItem('bozor-cart',JSON.stringify(compact))}catch{console.warn('Savatcha saqlanmadi')}},[cart])
 const notify=x=>{setToast(x);setTimeout(()=>setToast(''),1800)},addCart=p=>{setCart(current=>[...current,p]);notify(t('addedCart'))}
 const list=useMemo(()=>{let a=products.filter(p=>(cat==='Barchasi'||p.category===cat)&&p.name.toLowerCase().includes(query.toLowerCase()));if(sort==='cheap')a.sort((x,y)=>x.price-y.price);if(sort==='high')a.sort((x,y)=>y.price-x.price);if(sort==='rating')a.sort((x,y)=>y.rating-x.rating);return a},[products,cat,query,sort])
 const go=p=>{setPage(p);window.scrollTo({top:0,behavior:'smooth'})}
 return <div className="storeShell"><div className="top"><button onClick={()=>go('about')}>📍 {t('deliveryCity')}</button><div><button onClick={()=>go('about')}>{t('about')}</button><button onClick={()=>go('help')}>{t('help')}</button><label className="topLanguage"><span>{t('language')}</span><select value={lang} onChange={e=>setLang(e.target.value)}><option value="uz">UZ</option><option value="ru">RU</option><option value="en">EN</option></select></label></div></div><header><button className="logoButton" onClick={()=>go('home')}><Logo/></button><button className="catalog" onClick={()=>go('catalog')}>▦ {t('catalog')}</button><div className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&go('catalog')} placeholder={t('searchProducts')}/><button onClick={()=>go('catalog')}>{t('search')}</button></div><div className="actions"><ChatShortcut user={user} onOpen={()=>go('chat')}/><button onClick={()=>go('favorites')}>♡<small>{t('favorites')}</small><i>{favs.length||''}</i></button><button onClick={()=>go('cart')}>🛒<small>{t('cart')}</small><i>{cart.length||''}</i></button><button onClick={()=>go('profile')}>♙<small>{t('profile')}</small></button></div></header>
 {page==='home'&&<main className="home"><section className="hero"><div><span>{t('heroEyebrow')}</span><h1>{t('hero')}</h1><p>{t('heroText')}</p><button className="primary big" onClick={()=>go('catalog')}>{t('startShopping')} →</button><button className="ghost" onClick={()=>go('seller')}>{t('becomeSeller')}</button><div className="trust"><b>1000+<small>{t('products')}</small></b><b>24/7<small>{t('support')}</small></b><b>100%<small>{t('safe')}</small></b></div></div><div className="heroPhoto"><img src="/products/fashion.png" alt="Bozorly"/><span>{t('newCollection')}</span></div></section><section className="catSec"><div className="title"><div><span>{t('categories')}</span><h2>{t('whatLooking')}</h2></div><button onClick={()=>go('catalog')}>{t('viewAll')} →</button></div><div className="cats">{categories.map((c,i)=><button key={c} onClick={()=>{setCat(c);go('catalog')}}><i>{['✦','⌁','◌','⌂','⚡','◇','▤','◈'][i]}</i><b>{trCat(c,lang)}</b><small>{c==='Barchasi'?1000:Math.round(1000/7)} {t('products')}</small></button>)}</div></section><ProductSection title={t('popularProducts')} list={list.slice(0,8)} {...{favs,setFavs,addCart,setSelected,lang}}/><section className="seller"><div><span>{t('sellersFor')}</span><h2>{t('growBusiness')}</h2><p>{t('reachBuyers')}</p><button onClick={()=>go('seller')}>{t('startSelling')} →</button></div><img src="/products/home.png" alt="Bozorly"/></section></main>}
 {(page==='catalog'||page==='favorites')&&<main className="subpage"><PageTitle title={page==='catalog'?t('catalog'):t('favorites')} back={()=>go('home')}/>{page==='catalog'&&<div className="filters"><div>{categories.map(c=><button className={cat===c?'active':''} onClick={()=>{setCat(c);setLimit(20)}} key={c}>{trCat(c,lang)}</button>)}</div><select value={sort} onChange={e=>setSort(e.target.value)}><option value="popular">{t('popular')}</option><option value="cheap">{t('cheapFirst')}</option><option value="high">{t('expensiveFirst')}</option><option value="rating">{t('rating')}</option></select></div>}<ProductSection title={page==='favorites'?t('selectedProducts'):`${list.length} ${t('products')}`} list={(page==='favorites'?products.filter(p=>favs.includes(p.id)):list).slice(0,limit)} {...{favs,setFavs,addCart,setSelected,lang}}/>{page==='catalog'&&limit<list.length&&<button className="more" onClick={()=>setLimit(limit+20)}>{t('showMore')} ({list.length-limit})</button>}</main>}
 {page==='cart'&&<CartPage cart={cart} setCart={setCart} user={user} go={go} notify={notify}/>}
 {page==='profile'&&<ProfilePage user={user} go={go} onPanel={onPanel} onLogout={onLogout}/>}
 {page==='seller'&&<SellerApply user={user} onPanel={onPanel} notify={notify}/>}
 {page==='help'&&<InfoPage type="help" go={go}/>} {page==='about'&&<InfoPage type="about" go={go}/>}
 {page==='chat'&&<main className="subpage chatPage"><PageTitle title={t('chats')} back={()=>go('home')}/><ChatCenter user={user}/></main>}
 <footer><Logo light/><p>{t('marketplaceFooter')}</p><nav><button onClick={()=>go('about')}>{t('about')}</button><button onClick={()=>go('seller')}>{t('sellers')}</button><button onClick={()=>go('help')}>{t('delivery')}</button><button onClick={()=>go('help')}>{t('help')}</button></nav><small>{t('rights')}</small></footer>
 <nav className="mobileDock" aria-label={t('navigation')}>
  <button className={page==='home'?'active':''} onClick={()=>go('home')}><span><DockIcon name="home"/></span><small>{t('home')}</small></button>
  <button className={page==='catalog'?'active':''} onClick={()=>go('catalog')}><span><DockIcon name="catalog"/></span><small>{t('catalog')}</small></button>
  <button className={page==='chat'?'active':''} onClick={()=>go('chat')}><span><DockIcon name="chat"/></span><small>{t('chats')}</small></button>
  <button className={page==='cart'?'active':''} onClick={()=>go('cart')}><span><DockIcon name="cart"/></span><small>{t('cart')}</small>{cart.length>0&&<i>{cart.length>99?'99+':cart.length}</i>}</button>
  <button className={page==='profile'?'active':''} onClick={()=>go('profile')}><span><DockIcon name="profile"/></span><small>{t('profile')}</small></button>
 </nav>
 {selected&&<ProductDetail product={selected} user={user} lang={lang} close={()=>setSelected(null)} addCart={addCart}/>} {toast&&<div className="toast">✓ {toast}</div>}</div>
}
function ProductSection({title,list,favs,setFavs,addCart,setSelected,lang='uz'}){const {t}=useI18n();return <section className="products"><div className="prodHead"><div><span>{t('recommended')}</span><h2>{title}</h2></div></div>{list.length?<div className="grid">{list.map(p=><Card key={p.id} p={p} open={setSelected} {...{favs,setFavs,addCart,lang}}/>)}</div>:<Empty title={t('noProducts')} text={t('chooseCatalog')}/ >}</section>}
function ProductDetail({product,user,lang,close,addCart}){
 const {t}=useI18n()
 const [tab,setTab]=useState('info'),[reviews,setReviews]=useState([]),[text,setText]=useState(''),[error,setError]=useState(''),[sending,setSending]=useState(false)
 useEffect(()=>{
  let active=true
  api('/reviews?productId='+encodeURIComponent(product.id)).then(items=>{if(active)setReviews(items)}).catch(err=>{if(active)setError(err.message)})
  return ()=>{active=false}
 },[product.id])
 useEffect(()=>{const escape=e=>{if(e.key==='Escape')close()};window.addEventListener('keydown',escape);return()=>window.removeEventListener('keydown',escape)},[close])
 const sendReview=async e=>{
  e.preventDefault();if(!text.trim()||sending)return
  setSending(true);setError('')
  try{const review=await api('/reviews',{method:'POST',body:JSON.stringify({productId:product.id,text:text.trim(),rating:5})});setReviews(previous=>[...previous,review]);setText('')}
  catch(err){setError(err.message)}finally{setSending(false)}
 }
 return <div className="shade" onMouseDown={close}><div className="detail socialDetail" role="dialog" aria-modal="true" aria-label={trProduct(product.name,lang)} onMouseDown={e=>e.stopPropagation()}>
  <button className="x" aria-label={t('closeProduct')} onClick={close}>×</button><ProductImage p={product}/>
  <div><small>{trCat(product.category,lang)}</small><h2>{trProduct(product.name,lang)}</h2><b className="stars">★ {product.rating} ({reviews.length} {t('comments').toLocaleLowerCase()})</b>
  <div className="detailTabs"><button className={tab==='info'?'active':''} onClick={()=>setTab('info')}>{t('info')}</button><button className={tab==='reviews'?'active':''} onClick={()=>setTab('reviews')}>{t('comments')}</button><button className={tab==='chat'?'active':''} onClick={()=>setTab('chat')}>{t('chat')}</button></div>
  {tab==='info'&&<><p>{t('qualityText')}</p><strong>{money(product.price)}</strong><small>{t('seller')}: {product.seller} · {t('inStock')} {product.stock} {t('pieces')}</small><button className="primary" onClick={()=>{addCart(product);close()}}>{t('addCart')}</button><button className="catalog" onClick={()=>setTab('chat')}>{t('writeSeller')}</button></>}
  {tab==='reviews'&&<div className="thread">{error&&<p role="alert" className="formError">{error}</p>}{reviews.map(r=><div className="review" key={r.id}><b>{r.user} ★★★★★</b><p>{r.text}</p></div>)}<form onSubmit={sendReview}><input required aria-label={t('writeComment')} maxLength={2000} value={text} onChange={e=>setText(e.target.value)} placeholder={t('writeComment')}/><button disabled={sending||!text.trim()}>{t('send')}</button></form></div>}
  {tab==='chat'&&<ChatCenter user={user} compact target={{sellerId:product.sellerId,seller:product.seller,productId:product.id,productName:product.name}}/>}
  </div></div></div>
}
function PageTitle({title,back}){const {t}=useI18n();return <div className="pageTitle"><button onClick={back}>← {t('home')}</button><h1>{title}</h1></div>}
function Empty({title,text}){return <div className="emptyState"><i>◇</i><h2>{title}</h2><p>{text}</p></div>}

function CartPage({cart,setCart,user,go,notify}){const {t}=useI18n(),[checkout,setCheckout]=useState(false),[done,setDone]=useState(false),[error,setError]=useState(''),total=cart.reduce((s,p)=>s+p.price,0);const order=async e=>{e.preventDefault();setError('');const f=new FormData(e.currentTarget);try{await api('/orders',{method:'POST',body:JSON.stringify({phone:f.get('phone'),address:f.get('address'),payment:f.get('payment'),items:cart.map(p=>({id:p.id,name:p.name,price:p.price,seller:p.seller,sellerId:p.sellerId}))})});setDone(true);notify(t('orderSent'))}catch(err){setError(err.message)}};if(done)return <main className="subpage"><Empty title={t('orderAccepted')} text={t('operatorContact')}/><button className="primary center" onClick={()=>{setCart([]);go('home')}}>{t('toHome')}</button></main>;return <main className="subpage"><PageTitle title={checkout?t('checkout'):t('cart')} back={()=>checkout?setCheckout(false):go('home')}/>{checkout?<form className="checkout" onSubmit={order}><label>{t('name')}<input required defaultValue={user.name}/></label><label>{t('phone')}<input name="phone" type="tel" required defaultValue={user.phone||''} placeholder="+998 90 123 45 67"/></label><label>{t('address')}<textarea name="address" required placeholder={t('addressPlaceholder')}/></label><label>{t('payment')}<select name="payment"><option>{t('cashDelivery')}</option><option>Uzcard / Humo</option><option>Visa / Mastercard</option></select></label><b>{t('total')}: {money(total)}</b>{error&&<div className="formError">{error}</div>}<button className="primary full">{t('placeOrder')}</button></form>:cart.length?<div className="cartLayout"><section className="cartList">{cart.map((p,i)=><div className="cartItem" key={i}><ProductImage p={p}/><div><b>{p.name}</b><small>{p.category}</small></div><strong>{money(p.price)}</strong><button onClick={()=>setCart(cart.filter((_,x)=>x!==i))}>×</button></div>)}</section><aside className="summary"><h3>{t('order')}</h3><p>{t('products')} <b>{cart.length}</b></p><p>{t('delivery')} <b>{t('free')}</b></p><hr/><p className="sum">{t('total')} <b>{money(total)}</b></p><button className="primary full" onClick={()=>setCheckout(true)}>{t('checkout')} →</button><button className="clearCart" onClick={()=>setCart([])}>{t('clearCart')}</button></aside></div>:<Empty title={t('emptyCart')} text={t('addFromCatalog')}/>}</main>}

function ProfilePage({user,go,onPanel,onLogout}){const {t}=useI18n();return <main className="subpage narrow"><PageTitle title={t('myProfile')} back={()=>go('home')}/><section className="profilePage"><div className="avatar">{user.name[0]}</div><h2>{user.name}</h2><p>{user.email}</p><span className="roleTag">{user.role==='admin'?t('admin'):user.role==='seller'?t('sellerRole'):t('buyer')}</span><div className="profileMenu"><button onClick={()=>go('chat')}>✉ {t('myChats')} <span>→</span></button>{user.role==='admin'&&<button onClick={()=>onPanel('users')}>♙ {t('usersLogins')} <span>→</span></button>}<button onClick={onPanel}>▦ {t('dashboard')} <span>→</span></button><button onClick={()=>go('cart')}>⌑ {t('myCart')} <span>→</span></button><button onClick={()=>go('favorites')}>♡ {t('myFavorites')} <span>→</span></button><button onClick={()=>go('seller')}>▣ {t('becomeSeller')} <span>→</span></button></div><button className="logout" onClick={onLogout}>{t('logout')}</button></section></main>}

function SellerApply({user,onPanel,notify}){const {t}=useI18n(),[status,setStatus]=useState(null),[error,setError]=useState(''),[refreshing,setRefreshing]=useState(false);const refresh=useCallback(async()=>{setRefreshing(true);try{const apps=await api('/seller-applications');setStatus(apps.filter(x=>String(x.userId)===String(user.id)).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)))[0]?.status||null);setError('')}catch(err){setError(err.message)}finally{setRefreshing(false)}},[user.id]);useEffect(()=>{const initial=setTimeout(refresh,0),unsubscribe=subscribeRealtime(refresh),interval=setInterval(refresh,15000);return()=>{clearTimeout(initial);unsubscribe();clearInterval(interval)}},[refresh]);if(user.role==='admin'||user.role==='seller'||status==='approved')return <main className="subpage narrow"><PageTitle title={t('sellerCenter')} back={()=>history.back()}/><section className="applyBox approvedBox"><i>✓</i><h2>{t('sellerReady')}</h2><p>{t('sellerReadyText')}</p><button className="primary" onClick={onPanel}>{t('enterSellerPanel')}</button></section></main>;if(status==='pending')return <main className="subpage narrow"><PageTitle title={t('sellerCenter')} back={()=>history.back()}/><section className="applyBox pendingBox"><i>◷</i><h2>{t('applicationPending')}</h2><p>{t('applicationPendingText')}</p><button className="statusRefresh" disabled={refreshing} onClick={refresh}>↻ {t('refreshStatus')}</button>{error&&<div className="formError">{error}</div>}</section></main>;const apply=async e=>{e.preventDefault();setError('');const f=new FormData(e.currentTarget);try{await api('/seller-applications',{method:'POST',body:JSON.stringify({shop:f.get('shop'),phone:f.get('phone'),products:f.get('products')})});setStatus('pending');notify(t('applicationSent'))}catch(err){setError(err.message)}};return <main className="subpage narrow"><PageTitle title={t('becomeSeller')} back={()=>history.back()}/><form className="checkout sellerApplication" onSubmit={apply}><div className="applicationIcon">▣</div><h2>{t('openStoreApplication')}</h2><label>{t('storeName')}<input name="shop" required placeholder={t('storeExample')}/></label><label>{t('phone')}<input name="phone" type="tel" required defaultValue={user.phone||''} placeholder="+998 90 123 45 67"/></label><label>{t('plannedProducts')}<textarea name="products" required placeholder={t('productTypes')}/></label>{error&&<div className="formError">{error}</div>}<button className="primary full">{t('submitApplication')} →</button></form></main>}
function InfoPage({type,go}){const {t,lang}=useI18n(),help=type==='help',faq=lang==='ru'?[['Как оформить заказ?','Добавьте товар в корзину и нажмите кнопку оформления заказа.'],['Сколько длится доставка?','1–2 дня по Ташкенту и 2–4 рабочих дня по регионам.'],['Можно вернуть товар?','Да, товар можно вернуть в течение 14 дней.'],['Способы оплаты','Наличные, Uzcard, Humo, Visa и Mastercard.']]:lang==='en'?[['How do I place an order?','Add a product to your cart and select checkout.'],['How long does delivery take?','1–2 days in Tashkent and 2–4 business days in other regions.'],['Can I return an item?','Yes, items can be returned within 14 days.'],['Payment methods','Cash, Uzcard, Humo, Visa and Mastercard.']]:[['Buyurtma qanday beriladi?','Mahsulotni savatchaga qo‘shib, rasmiylashtirish tugmasini bosing.'],['Yetkazish qancha vaqt?','Toshkent bo‘ylab 1–2, viloyatlarga 2–4 ish kuni.'],['Qaytarish mumkinmi?','Ha, 14 kun ichida qaytarish mumkin.'],['To‘lov turlari','Naqd, Uzcard, Humo, Visa va Mastercard.']];return <main className="subpage narrow"><PageTitle title={help?t('helpCenter'):t('aboutBozorly')} back={()=>go('home')}/>{help?<section className="faq">{faq.map(x=><details key={x[0]}><summary>{x[0]}</summary><p>{x[1]}</p></details>)}</section>:<section className="aboutPage"><img src="/products/home.png" alt="Bozorly"/><h2>{t('easierTrade')}</h2><p>{t('aboutText')}</p><div className="aboutStats"><b>1000+<small>{t('products')}</small></b><b>500+<small>{t('customers')}</small></b><b>24/7<small>{t('support')}</small></b></div></section>}</main>}

function Dashboard({user,products,setProducts,onBack,onLogout,initialTab='overview'}){
 const {t,lang,setLang}=useI18n(),role=user.role,[tab,setTab]=useState(initialTab),[applications,setApplications]=useState([]),[approving,setApproving]=useState(null),[name,setName]=useState(''),[price,setPrice]=useState(''),[photo,setPhoto]=useState(''),[wallet,setWallet]=useState({balance:0,withdrawals:[]}),[orders,setOrders]=useState([]),[currentPassword,setCurrentPassword]=useState(''),[newPassword,setNewPassword]=useState(''),[confirmPassword,setConfirmPassword]=useState(''),[passwordMessage,setPasswordMessage]=useState(''),[passwordError,setPasswordError]=useState('')
 const refreshDashboard=useCallback(()=>{if(role==='admin')api('/seller-applications').then(setApplications).catch(()=>{});api('/orders').then(setOrders).catch(()=>{});if(role!=='buyer')api('/wallet?seller='+encodeURIComponent(user.name)).then(setWallet).catch(()=>{})},[role,user.name])
 useEffect(()=>{const initial=setTimeout(refreshDashboard,0),unsubscribe=subscribeRealtime(refreshDashboard),interval=setInterval(refreshDashboard,20000);return()=>{clearTimeout(initial);unsubscribe();clearInterval(interval)}},[refreshDashboard])
 const nav=role==='admin'?[['overview',t('overview')],['chat',t('chats')],['sellers',t('sellers')],['products',t('productsNav')],['orders',t('orders')],['users',t('users')],['settings',t('settings')]]:role==='seller'?[['overview',t('overview')],['chat',t('chats')],['products',t('myProducts')],['orders',t('orders')],['finance',t('finance')],['settings',t('storeSettings')]]:[['overview',t('overview')],['chat',t('chats')],['orders',t('myOrders')],['favorites',t('favorites')],['addresses',t('addresses')],['seller',t('becomeSeller')]]
 const approve=async(a,ok)=>{if(approving)return;setApproving(a.id);try{const updated=await api('/seller-applications/'+encodeURIComponent(a.id),{method:'PATCH',body:JSON.stringify({status:ok?'approved':'rejected'})});setApplications(previous=>previous.map(x=>x.id===a.id?updated:x))}catch(err){alert(err.message)}finally{setApproving(null)}}
 const choosePhoto=e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>2500000){alert('Rasm hajmi 2.5 MB dan kichik bo‘lsin');e.target.value='';return}const reader=new FileReader();reader.onload=()=>setPhoto(reader.result);reader.readAsDataURL(file)}
 const add=async e=>{e.preventDefault();if(!name||!price)return;try{const product=await api('/products',{method:'POST',body:JSON.stringify({name,price:Number(price),image:photo,fallback:fallback.Elektronika})});setProducts(previous=>[product,...previous]);setName('');setPrice('');setPhoto('')}catch(err){alert(err.message)}}
 const changePassword=async e=>{e.preventDefault();setPasswordMessage('');setPasswordError('');if(newPassword!==confirmPassword){setPasswordError('Yangi parollar bir xil emas.');return}try{await api('/account/password',{method:'POST',body:JSON.stringify({currentPassword,newPassword})});setCurrentPassword('');setNewPassword('');setConfirmPassword('');setPasswordMessage('Parol muvaffaqiyatli almashtirildi.')}catch(err){setPasswordError(err.message)}}
 const withdraw=async()=>{const raw=prompt('Yechiladigan summa (so‘m):');if(!raw)return;try{const result=await api('/withdraw',{method:'POST',body:JSON.stringify({seller:user.name,amount:Number(raw)})});setWallet({...wallet,balance:result.balance,withdrawals:[...wallet.withdrawals,result]});alert('Demo yechish bajarildi. Pul hech qayerga yuborilmadi.')}catch(err){alert(err.message)}}
 return <div className="panel"><aside><button className="logoButton" onClick={onBack}><Logo light/></button><div className="profile"><i>{user.name[0]}</i><b>{user.name}</b><small>{role==='admin'?t('admin'):role==='seller'?t('sellerRole'):t('buyer')}</small></div><nav>{nav.map(x=><button className={tab===x[0]?'active':''} onClick={()=>setTab(x[0])} key={x[0]}>{x[1]}</button>)}</nav><label className="panelLanguage"><span>{t('language')}</span><select value={lang} onChange={e=>setLang(e.target.value)}><option value="uz">UZ</option><option value="ru">RU</option><option value="en">EN</option></select></label><button className="back" onClick={onBack}>← {t('backStore')}</button><button className="back danger" onClick={onLogout}>{t('logout')}</button></aside><main><div className="dashHead"><div><span>{role.toUpperCase()} PANEL</span><h1>{nav.find(x=>x[0]===tab)?.[1]}</h1><p>{t('goodDay')}, {user.name}!</p></div></div>{tab==='overview'&&<><div className="stats">{(role==='buyer'?[['🛒',t('orders'),'4'],['♡',t('favorites'),'12'],['🎁','Bonus','24 500'],['⭐',t('rating'),'Silver']]:[['💰','Sales','24.8 mln'],['📦',t('orders'),'1,284'],['👥',t('customers'),'842'],['⭐',t('rating'),'4.9']]).map(x=><div key={x[1]}><i>{x[0]}</i><span>{x[1]}</span><b>{x[2]}</b><em>↗ active</em></div>)}</div><section className="manage"><h2>{t('activity')}</h2><p>{t('accountActive')}</p></section></>}
 {tab==='sellers'&&<section className="manage"><h2>{t('allStoresApplications')} ({applications.length})</h2>{applications.length?applications.map(a=><div className="application" key={a.id}><div><b>▣ {a.shop}</b><small>{t('owner')}: {a.name} · {a.email} · {a.phone} · {t('goods')}: {a.products}</small></div><span className={'status '+a.status}>{a.status==='approved'?t('activeStore'):a.status==='rejected'?t('rejected'):t('underReview')}</span>{a.status==='pending'&&<><button className="approve" disabled={approving===a.id} onClick={()=>approve(a,true)}>✓ {approving===a.id?t('waiting'):t('approve')}</button><button className="reject" disabled={approving===a.id} onClick={()=>approve(a,false)}>× {t('reject')}</button></>}</div>):<Empty title={t('noStores')} text={t('applicationsAppear')}/>}</section>}
 {tab==='products'&&<section className="manage"><h2>{role==='admin'?t('allProducts'):t('myProducts')}</h2><form className="add productAdd" onSubmit={add}><div className="uploadPhoto"><label>{photo?<img src={photo} alt={t('productName')}/>:<span>📷<small>Photo</small></span>}<input type="file" accept="image/png,image/jpeg,image/webp" onChange={choosePhoto}/></label>{photo&&<button type="button" onClick={()=>setPhoto('')}>×</button>}</div><input value={name} onChange={e=>setName(e.target.value)} placeholder={t('productName')}/><input type="number" value={price} onChange={e=>setPrice(e.target.value)} placeholder={t('price')}/><button className="primary">{t('addProduct')}</button></form>{products.filter(p=>role==='admin'||String(p.sellerId)===String(user.id)||p.seller===user.name).slice(0,15).map(p=><div className="row" key={p.id}><ProductImage p={p}/><div><b>{p.name}</b><small>{p.seller} · {p.stock} {t('pieces')}</small></div><strong>{money(p.price)}</strong><span>{t('onSale')}</span><button onClick={async()=>{try{await api('/products/'+encodeURIComponent(p.id),{method:'DELETE'});setProducts(previous=>previous.filter(x=>x.id!==p.id))}catch(err){alert(err.message)}}}>{t('delete')}</button></div>)}</section>}
 {tab==='orders'&&<section className="manage"><h2>{role==='buyer'?t('myOrders'):t('soldProducts')}</h2>{orders.filter(o=>role==='admin'||(role==='buyer'?String(o.userId)===String(user.id):o.items.some(i=>String(i.sellerId)===String(user.id)||i.seller===user.name))).map(o=><div className="simpleRow" key={o.id}><div><b>#{o.id} · {o.user}</b><small>{o.items.filter(i=>role!=='seller'||String(i.sellerId)===String(user.id)||i.seller===user.name).map(i=>i.name).join(', ')}</small></div><strong>{money(role==='seller'?o.items.filter(i=>String(i.sellerId)===String(user.id)||i.seller===user.name).reduce((s,i)=>s+i.price,0):o.total)}</strong><span>{o.status}</span></div>)}</section>}
 {tab==='users'&&user.role==='admin'&&<AdminAccounts/>}
 {tab==='chat'&&<ChatCenter user={user}/>}

 {tab==='finance'&&<section className="manage"><h2>{t('financeWallet')}</h2><div className="financeBig">{money(wallet.balance)} <small>{t('availableBalance')}</small></div><button className="primary" onClick={withdraw}>{t('demoWithdraw')}</button><p className="demoWarning">{t('demoWarning')}</p>{wallet.withdrawals.map(w=><div className="simpleRow" key={w.id}><b>{t('withdrawn')}: {money(w.amount)}</b><span>{w.status}</span></div>)}</section>}
 {tab==='addresses'&&<section className="manage settings"><h2>{t('deliveryAddress')}</h2><label>{t('address')}<input placeholder={t('addressPlaceholder')}/></label><button className="primary">{t('save')}</button></section>}
 {tab==='favorites'&&<section className="manage"><h2>{t('favorites')}</h2><p>{t('favoriteText')}</p></section>}
 {tab==='seller'&&<section className="manage"><h2>{t('becomeSeller')}</h2><p>{t('sellerInstruction')}</p></section>}
 {tab==='settings'&&<section className="manage settings"><h2>{t('settings')}</h2><label>{t('name')}<input defaultValue={user.name}/></label><label>Email<input defaultValue={user.email}/></label><button className="primary">{t('save')}</button><form className="passwordChange" onSubmit={changePassword}><h3>{t('changePassword')}</h3><label>{t('currentPassword')}<input required type="password" value={currentPassword} onChange={e=>setCurrentPassword(e.target.value)}/></label><label>{t('newPassword')}<input required minLength="4" type="password" value={newPassword} onChange={e=>setNewPassword(e.target.value)}/></label><label>{t('confirmPassword')}<input required minLength="4" type="password" value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)}/></label>{passwordError&&<div className="formError">{passwordError}</div>}{passwordMessage&&<p role="status">{passwordMessage}</p>}<button className="primary">{t('changePassword')}</button></form></section>}</main></div>
}

function Application(){
 const {lang,setLang,t}=useI18n()
 const [user,setUser]=useState(null),[checking,setChecking]=useState(true),[sessionError,setSessionError]=useState(''),[attempt,setAttempt]=useState(0)
 const [products,setProducts]=useState(()=>initialProducts)
 const [panel,setPanel]=useState(null)
 const userId=user?.id
 useEffect(()=>{
  if (!userId) return
  let active = true
  const loadProducts = () => api('/products').then(items => { if (active) setProducts(previous => [...items, ...previous.filter(item => !item.custom || !items.some(serverItem => String(serverItem.id) === String(item.id)))]) }).catch(() => {})
  const migrateLegacyProducts = async () => {
   let legacy=[]
   try { if (!localStorage.getItem('bozor-products-migrated')) legacy=savedArray('bozor-custom-products') } catch {}
   if (legacy.length) {
    try {
     await Promise.all(legacy.map(product=>api('/products',{method:'POST',body:JSON.stringify({clientId:String(product.id),name:product.name,price:Number(product.price),image:product.image,fallback:product.fallback})})))
     localStorage.setItem('bozor-products-migrated','1')
    } catch {}
   }
   loadProducts()
  }
  migrateLegacyProducts()
  const interval = setInterval(loadProducts, 5000)
  return () => { active = false; clearInterval(interval) }
 },[userId])
 useEffect(()=>{
  let active=true
  api('/me').then(fresh=>{if(active){setUser(fresh);setSessionError('')}}).catch(err=>{if(active&&err.status!==401)setSessionError(err.message)}).finally(()=>{if(active)setChecking(false)})
  return ()=>{active=false}
 },[attempt])
 useEffect(()=>{
  if(!userId)return
  let active=true
  const refresh=()=>api('/me').then(fresh=>{if(active)setUser(fresh)}).catch(err=>{if(active&&err.status===401){setUser(null);setPanel(null)}})
  const expired=()=>{setUser(null);setPanel(null)}
  const unsubscribe=subscribeRealtime(refresh)
  const interval=setInterval(refresh,15000)
  window.addEventListener('focus',refresh);window.addEventListener('bozor-session-expired',expired)
  return ()=>{active=false;unsubscribe();clearInterval(interval);window.removeEventListener('focus',refresh);window.removeEventListener('bozor-session-expired',expired)}
 },[userId])
 const auth=u=>{setUser(u);setSessionError('');setPanel(null)}
 const logout=async()=>{try{await api('/logout',{method:'POST',body:'{}'});setUser(null);setPanel(null);setSessionError('')}catch(err){setSessionError(err.message)}}
 const openPanel=tab=>setPanel(typeof tab==='string'?tab:'overview')
 if(checking)return <main className="authSide"><p role="status">{t('checkingAccount')}</p></main>
 if(sessionError&&!user)return <main className="authSide"><section className="authBox"><Logo/><p role="alert">{sessionError}</p><button className="primary" onClick={()=>{setChecking(true);setAttempt(value=>value+1)}}>{t('reconnect')}</button></section></main>
 return <>{sessionError&&<div role="alert" className="formError">{sessionError}</div>}{!user?<AuthPage onAuth={auth}/>:panel?<Dashboard key={user.id+':'+user.role} {...{user,products,setProducts}} initialTab={panel} onBack={()=>setPanel(null)} onLogout={logout}/>:<Store key={user.id} {...{products,user,lang,setLang}} onLogout={logout} onPanel={openPanel}/>}</>
}

export default function App(){return <I18nProvider><Application/></I18nProvider>}
    
import {api,subscribeRealtime} from './api.js'
import ChatCenter, {ChatShortcut} from './ChatCenter.jsx'
import AdminAccounts from './AdminAccounts.jsx'
