import {useEffect,useMemo,useState} from 'react'
import './App.css'
import './extra.css'

const categories=['Barchasi','Elektronika','Kiyim','Uy va bog‘','Sport','Go‘zallik','Kitoblar','Avto']
const catalog=[
 ['Elektronika','Simsiz quloqchin','wireless,headphones'],['Elektronika','Smart soat','smartwatch'],['Elektronika','Mexanik klaviatura','mechanical,keyboard'],['Elektronika','Portativ kolonka','portable,speaker'],['Elektronika','Powerbank','powerbank'],
 ['Kiyim','Premium huddi','hoodie'],['Kiyim','Yengil krossovka','sneakers'],['Kiyim','Denim kurtka','denim,jacket'],['Kiyim','Teri sumka','leather,handbag'],['Kiyim','Klassik ko‘ylak','dress,shirt'],
 ['Uy va bog‘','Aqlli chiroq','table,lamp'],['Uy va bog‘','Robot changyutgich','robot,vacuum'],['Uy va bog‘','Qahva qaynatgich','coffee,maker'],['Uy va bog‘','Oshxona to‘plami','kitchenware'],['Uy va bog‘','Yumshoq kreslo','armchair'],
 ['Sport','Fitness ganteli','dumbbells'],['Sport','Futbol to‘pi','soccer,ball'],['Sport','Yoga gilamchasi','yoga,mat'],['Sport','Sport ryukzagi','sports,backpack'],['Sport','Tennis raketkasi','tennis,racket'],
 ['Go‘zallik','Parfyum','perfume,bottle'],['Go‘zallik','Yuz kremi','face,cream'],['Go‘zallik','Soch feni','hair,dryer'],['Go‘zallik','Kosmetika sumkasi','cosmetic,bag'],['Go‘zallik','Manikyur to‘plami','manicure,set'],
 ['Kitoblar','Dasturlash kitobi','programming,book'],['Kitoblar','Biznes kitobi','business,book'],['Kitoblar','Jahon adabiyoti','novel,book'],['Kitoblar','Ingliz tili kitobi','english,textbook'],['Kitoblar','Dizayn kitobi','design,book'],
 ['Avto','Video registrator','dash,camera'],['Avto','Telefon ushlagich','car,phone,holder'],['Avto','Avto changyutgich','car,vacuum'],['Avto','Asboblar to‘plami','car,toolkit'],['Avto','Avto kompressor','car,compressor']
]
const fallback={Elektronika:'/products/electronics.png',Kiyim:'/products/fashion.png','Uy va bog‘':'/products/home.png',Sport:'/products/sport.png','Go‘zallik':'/products/beauty.png',Kitoblar:'/products/books.png',Avto:'/products/auto.png'}
const initialProducts=Array.from({length:1000},(_,i)=>{const [category,base,term]=catalog[i%catalog.length];return{id:i+1,name:base+' '+String.fromCharCode(65+i%6)+(Math.floor(i/catalog.length)+1),category,price:49000+(i*7919)%4950000,old:i%3===0?89000+(i*8941)%5300000:0,rating:(4.1+i%9/10).toFixed(1),reviews:12+i*17%870,stock:5+i*13%95,seller:['TechHouse','Moda Uz','Baraka Shop','Smart Store'][i%4],image:`https://loremflickr.com/600/480/${term}?lock=${i+1}`,fallback:fallback[category]}})
const money=n=>new Intl.NumberFormat('uz-UZ').format(n)+' so‘m'
const savedArray=key=>{try{const value=JSON.parse(localStorage.getItem(key)||'[]');return Array.isArray(value)?value:[]}catch{return []}}

const copy={
 uz:{search:'Mahsulotlarni qidiring...',catalog:'Katalog',favorites:'Sevimli',cart:'Savatcha',profile:'Profil',hero:'Kerakli narsani oson toping.',heroText:'1000 dan ortiq mahsulot, ishonchli sotuvchilar va tezkor yetkazib berish.',start:'Xaridni boshlash',popular:'Ommabop mahsulotlar',all:'Barchasi',products:'mahsulot',add:'Savatchaga qo‘shish',reviews:'sharh'},
 ru:{search:'Поиск товаров...',catalog:'Каталог',favorites:'Избранное',cart:'Корзина',profile:'Профиль',hero:'Найдите всё, что вам нужно.',heroText:'Более 1000 товаров, надежные продавцы и быстрая доставка.',start:'Начать покупки',popular:'Популярные товары',all:'Все',products:'товаров',add:'Добавить в корзину',reviews:'отзывов'},
 en:{search:'Search products...',catalog:'Catalog',favorites:'Favorites',cart:'Cart',profile:'Profile',hero:'Find everything you need.',heroText:'Over 1000 products, trusted sellers and fast delivery.',start:'Start shopping',popular:'Popular products',all:'All',products:'products',add:'Add to cart',reviews:'reviews'}
}
const categoryI18n={Elektronika:{ru:'Электроника',en:'Electronics'},Kiyim:{ru:'Одежда',en:'Fashion'},'Uy va bog‘':{ru:'Дом и сад',en:'Home & garden'},Sport:{ru:'Спорт',en:'Sports'},'Go‘zallik':{ru:'Красота',en:'Beauty'},Kitoblar:{ru:'Книги',en:'Books'},Avto:{ru:'Авто',en:'Automotive'},Barchasi:{ru:'Все',en:'All'}}
const productI18n={
 'Simsiz quloqchin':['Беспроводные наушники','Wireless headphones'],'Smart soat':['Умные часы','Smart watch'],'Mexanik klaviatura':['Механическая клавиатура','Mechanical keyboard'],'Portativ kolonka':['Портативная колонка','Portable speaker'],Powerbank:['Повербанк','Power bank'],
 'Premium huddi':['Премиум худи','Premium hoodie'],'Yengil krossovka':['Лёгкие кроссовки','Lightweight sneakers'],'Denim kurtka':['Джинсовая куртка','Denim jacket'],'Teri sumka':['Кожаная сумка','Leather bag'],'Klassik ko‘ylak':['Классическая рубашка','Classic shirt'],
 'Aqlli chiroq':['Умная лампа','Smart lamp'],'Robot changyutgich':['Робот-пылесос','Robot vacuum'],'Qahva qaynatgich':['Кофеварка','Coffee maker'],'Oshxona to‘plami':['Кухонный набор','Kitchen set'],'Yumshoq kreslo':['Мягкое кресло','Soft armchair'],
 'Fitness ganteli':['Фитнес-гантели','Fitness dumbbells'],'Futbol to‘pi':['Футбольный мяч','Football'],'Yoga gilamchasi':['Коврик для йоги','Yoga mat'],'Sport ryukzagi':['Спортивный рюкзак','Sports backpack'],'Tennis raketkasi':['Теннисная ракетка','Tennis racket'],
 Parfyum:['Парфюм','Perfume'],'Yuz kremi':['Крем для лица','Face cream'],'Soch feni':['Фен для волос','Hair dryer'],'Kosmetika sumkasi':['Косметичка','Cosmetic bag'],'Manikyur to‘plami':['Маникюрный набор','Manicure set'],
 'Dasturlash kitobi':['Книга по программированию','Programming book'],'Biznes kitobi':['Книга о бизнесе','Business book'],'Jahon adabiyoti':['Мировая литература','World literature'],'Ingliz tili kitobi':['Учебник английского','English textbook'],'Dizayn kitobi':['Книга по дизайну','Design book'],
 'Video registrator':['Видеорегистратор','Dash camera'],'Telefon ushlagich':['Держатель телефона','Phone holder'],'Avto changyutgich':['Автопылесос','Car vacuum'],'Asboblar to‘plami':['Набор инструментов','Tool kit'],'Avto kompressor':['Автокомпрессор','Car compressor']
}
const trCat=(name,lang)=>lang==='uz'?name:categoryI18n[name]?.[lang]||name
const trProduct=(name,lang)=>{if(lang==='uz')return name;const base=Object.keys(productI18n).find(x=>name.startsWith(x));return base?name.replace(base,productI18n[base][lang==='ru'?0:1]):name}

function Logo({light=false}){return <span className={'siteLogo '+(light?'light':'')}><i><b>B</b></i><strong>bozorly<span>.</span></strong></span>}
function ProductImage({p}){return <img src={p.image} alt={p.name} loading="lazy" onError={e=>{if(p.fallback&&!e.currentTarget.dataset.fallback){e.currentTarget.dataset.fallback='1';e.currentTarget.src=p.fallback}}}/>}

function AuthPage({onAuth}){
 const [login,setLogin]=useState(true),[form,setForm]=useState({login:'',name:'',email:'',phone:'',password:''}),[error,setError]=useState(''),[loading,setLoading]=useState(false)
 const submit=async e=>{e.preventDefault();setError('');setLoading(true);try{const u=login?await api('/login',{method:'POST',body:JSON.stringify({login:form.login,password:form.password})}):await api('/register',{method:'POST',body:JSON.stringify(form)});onAuth(u)}catch(err){setError(err.message)}finally{setLoading(false)}}
 return <main className="authPage"><section className="authVisual"><Logo light/><div className="authArt"><div className="visualOrb"></div><img src="/products/electronics.png" alt="Marketplace mahsulotlari"/><span className="visualBadge one">✓ Ishonchli sotuvchilar</span><span className="visualBadge two">⚡ Tezkor yetkazish</span></div><div><h1>Yangi avlod<br/><em>marketplace.</em></h1><p>Kerakli mahsulotni toping, xavfsiz xarid qiling yoki o‘z biznesingizni boshlang.</p></div></section><section className="authSide"><form className="authBox" onSubmit={submit}><Logo/><h2>{login?'Xush kelibsiz!':'Yangi hisob yarating'}</h2><p>{login?'Davom etish uchun hisobingizga kiring.':'Bozorly imkoniyatlaridan foydalanishni boshlang.'}</p><div className="authSwitch"><button type="button" className={login?'active':''} onClick={()=>setLogin(true)}>Kirish</button><button type="button" className={!login?'active':''} onClick={()=>setLogin(false)}>Ro‘yxatdan o‘tish</button></div>{!login&&<><label>Ism va familiya<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Ismingiz"/></label><label>Telefon raqami<input required type="tel" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="+998 90 123 45 67"/></label></>}<label>Email yoki login<input required value={login?form.login:form.email} onChange={e=>login?setForm({...form,login:e.target.value}):setForm({...form,email:e.target.value})} placeholder={login?'Email yoki Ubaydulloh':'email@example.com'}/></label><label>Parol<input required type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} placeholder="••••••••"/></label>{error&&<div className="formError">{error}</div>}<button disabled={loading} className="primary full">{loading?'Kutilmoqda...':login?'Tizimga kirish →':'Hisob yaratish →'}</button></form></section></main>
}

function Card({p,favs,setFavs,addCart,open,lang}){const liked=favs.includes(p.id),t=copy[lang];return <article className="card"><div className="pic" onClick={()=>open(p)}><ProductImage p={p}/>{p.old>0&&<span className="sale">−15%</span>}<button className={'heart '+(liked?'liked':'')} onClick={e=>{e.stopPropagation();setFavs(liked?favs.filter(x=>x!==p.id):[...favs,p.id])}}>{liked?'♥':'♡'}</button></div><div className="info"><small>{trCat(p.category,lang)}</small><h3 onClick={()=>open(p)}>{trProduct(p.name,lang)}</h3><div className="rating"><b>★ {p.rating}</b> ({p.reviews} {t.reviews})</div><div className="price"><div><strong>{money(p.price)}</strong>{p.old>0&&<del>{money(p.old)}</del>}</div><button aria-label={t.add} onClick={()=>addCart(p)}>＋</button></div></div></article>}


function Store({products,user,lang,setLang,onLogout,onPanel}){

 const t=copy[lang],[page,setPage]=useState('home'),[query,setQuery]=useState(''),[cat,setCat]=useState('Barchasi'),[sort,setSort]=useState('popular'),[limit,setLimit]=useState(20),[favs,setFavs]=useState(()=>savedArray('bozor-favs')),[cart,setCart]=useState(()=>savedArray('bozor-cart')),[selected,setSelected]=useState(null),[toast,setToast]=useState('')
 useEffect(()=>{try{localStorage.setItem('bozor-favs',JSON.stringify(favs))}catch{console.warn('Sevimlilar saqlanmadi')}},[favs]);useEffect(()=>{const compact=cart.map(p=>({...p,image:p.image?.startsWith('data:')?p.fallback:p.image}));try{localStorage.removeItem('bozor-cart');localStorage.setItem('bozor-cart',JSON.stringify(compact))}catch{console.warn('Savatcha saqlanmadi')}},[cart])
 const notify=x=>{setToast(x);setTimeout(()=>setToast(''),1800)},addCart=p=>{setCart(current=>[...current,p]);notify('Mahsulot savatchaga qo‘shildi')}
 const list=useMemo(()=>{let a=products.filter(p=>(cat==='Barchasi'||p.category===cat)&&p.name.toLowerCase().includes(query.toLowerCase()));if(sort==='cheap')a.sort((x,y)=>x.price-y.price);if(sort==='high')a.sort((x,y)=>y.price-x.price);if(sort==='rating')a.sort((x,y)=>y.rating-x.rating);return a},[products,cat,query,sort])
 const go=p=>{setPage(p);window.scrollTo({top:0,behavior:'smooth'})}
 return <div><div className="top"><button onClick={()=>go('about')}>📍 Toshkent · Yetkazib berish</button><div><button onClick={()=>go('about')}>Biz haqimizda</button><button onClick={()=>go('help')}>Yordam</button><select value={lang} onChange={e=>setLang(e.target.value)}><option value="uz">UZ</option><option value="ru">RU</option><option value="en">EN</option></select></div></div><header><button className="logoButton" onClick={()=>go('home')}><Logo/></button><button className="catalog" onClick={()=>go('catalog')}>▦ {t.catalog}</button><div className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&go('catalog')} placeholder={t.search}/><button onClick={()=>go('catalog')}>Qidirish</button></div><div className="actions"><ChatShortcut user={user} onOpen={()=>go('chat')}/><button onClick={()=>go('favorites')}>♡<small>{t.favorites}</small><i>{favs.length||''}</i></button><button onClick={()=>go('cart')}>🛒<small>{t.cart}</small><i>{cart.length||''}</i></button><button onClick={()=>go('profile')}>♙<small>{t.profile}</small></button></div></header>
 {page==='home'&&<main className="home"><section className="hero"><div><span>YANGI AVLOD MARKETPLACE</span><h1>{t.hero}</h1><p>{t.heroText}</p><button className="primary big" onClick={()=>go('catalog')}>{t.start} →</button><button className="ghost" onClick={()=>go('seller')}>Sotuvchi bo‘lish</button><div className="trust"><b>1000+<small>mahsulot</small></b><b>24/7<small>yordam</small></b><b>100%<small>xavfsiz</small></b></div></div><div className="heroPhoto"><img src="/products/fashion.png" alt="Bozorly mahsulotlari"/><span>Yangi kolleksiya</span></div></section><section className="catSec"><div className="title"><div><span>KATEGORIYALAR</span><h2>Nimani qidiryapsiz?</h2></div><button onClick={()=>go('catalog')}>Barchasini ko‘rish →</button></div><div className="cats">{categories.map((c,i)=><button key={c} onClick={()=>{setCat(c);go('catalog')}}><i>{['✦','⌁','◌','⌂','⚡','◇','▤','◈'][i]}</i><b>{c}</b><small>{c==='Barchasi'?1000:Math.round(1000/7)} mahsulot</small></button>)}</div></section><ProductSection title={t.popular} list={list.slice(0,8)} {...{favs,setFavs,addCart,setSelected,lang}}/><section className="seller"><div><span>SOTUVCHILAR UCHUN</span><h2>Biz bilan biznesingizni o‘stiring</h2><p>Millionlab xaridorlarga yetib boring. Ariza topshirish bepul.</p><button onClick={()=>go('seller')}>Sotishni boshlash →</button></div><img src="/products/home.png" alt="Sotuvchi mahsulotlari"/></section></main>}
 {(page==='catalog'||page==='favorites')&&<main className="subpage"><PageTitle title={page==='catalog'?t.catalog:t.favorites} back={()=>go('home')}/>{page==='catalog'&&<div className="filters"><div>{categories.map(c=><button className={cat===c?'active':''} onClick={()=>{setCat(c);setLimit(20)}} key={c}>{c}</button>)}</div><select value={sort} onChange={e=>setSort(e.target.value)}><option value="popular">Ommabop</option><option value="cheap">Avval arzon</option><option value="high">Avval qimmat</option><option value="rating">Reyting</option></select></div>}<ProductSection title={page==='favorites'?'Siz tanlagan mahsulotlar':list.length+' ta mahsulot'} list={(page==='favorites'?products.filter(p=>favs.includes(p.id)):list).slice(0,limit)} {...{favs,setFavs,addCart,setSelected,lang}}/>{page==='catalog'&&limit<list.length&&<button className="more" onClick={()=>setLimit(limit+20)}>Yana ko‘rsatish ({list.length-limit})</button>}</main>}
 {page==='cart'&&<CartPage cart={cart} setCart={setCart} user={user} go={go} notify={notify}/>}
 {page==='profile'&&<ProfilePage user={user} go={go} onPanel={onPanel} onLogout={onLogout}/>}
 {page==='seller'&&<SellerApply user={user} onPanel={onPanel} notify={notify}/>}
 {page==='help'&&<InfoPage type="help" go={go}/>} {page==='about'&&<InfoPage type="about" go={go}/>}
 {page==='chat'&&<main className="subpage chatPage"><PageTitle title="Chatlar" back={()=>go('home')}/><ChatCenter user={user}/></main>}
 <footer><Logo light/><p>O‘zbekistondagi zamonaviy va ishonchli marketplace.</p><nav><button onClick={()=>go('about')}>Biz haqimizda</button><button onClick={()=>go('seller')}>Sotuvchilar</button><button onClick={()=>go('help')}>Yetkazib berish</button><button onClick={()=>go('help')}>Yordam</button></nav><small>© 2026 Bozorly. Barcha huquqlar himoyalangan.</small></footer>
 {selected&&<ProductDetail product={selected} user={user} lang={lang} close={()=>setSelected(null)} addCart={addCart}/>} {toast&&<div className="toast">✓ {toast}</div>}</div>
}
function ProductSection({title,list,favs,setFavs,addCart,setSelected,lang='uz'}){return <section className="products"><div className="prodHead"><div><span>{lang==='ru'?'РЕКОМЕНДУЕМ':lang==='en'?'RECOMMENDED':'TAVSIYA ETAMIZ'}</span><h2>{title}</h2></div></div>{list.length?<div className="grid">{list.map(p=><Card key={p.id} p={p} open={setSelected} {...{favs,setFavs,addCart,lang}}/>)}</div>:<Empty title={lang==='ru'?'Товаров пока нет':lang==='en'?'No products yet':'Hozircha mahsulot yo‘q'} text="Katalogdan mahsulot tanlang."/ >}</section>}
function ProductDetail({product,user,lang,close,addCart}){
 const [tab,setTab]=useState('info'),[reviews,setReviews]=useState([]),[text,setText]=useState(''),[error,setError]=useState(''),[sending,setSending]=useState(false)
 useEffect(()=>{
  let active=true
  api('/reviews?productId='+encodeURIComponent(product.id)).then(items=>{if(active)setReviews(items)}).catch(err=>{if(active)setError(err.message)})
  return ()=>{active=false}
 },[product.id])
 useEffect(()=>{const escape=e=>{if(e.key==='Escape')close()};window.addEventListener('keydown',escape);return()=>window.removeEventListener('keydown',escape)},[close])
 const sendReview=async e=>{
  e.preventDefault();if(!text.trim()||sending)return
  setSending(true);setError('')
  try{const review=await api('/reviews',{method:'POST',body:JSON.stringify({productId:product.id,text:text.trim(),rating:5})});setReviews(previous=>[...previous,review]);setText('')}
  catch(err){setError(err.message)}finally{setSending(false)}
 }
 return <div className="shade" onMouseDown={close}><div className="detail socialDetail" role="dialog" aria-modal="true" aria-label={trProduct(product.name,lang)} onMouseDown={e=>e.stopPropagation()}>
  <button className="x" aria-label="Mahsulot oynasini yopish" onClick={close}>×</button><ProductImage p={product}/>
  <div><small>{trCat(product.category,lang)}</small><h2>{trProduct(product.name,lang)}</h2><b className="stars">★ {product.rating} ({reviews.length} izoh)</b>
  <div className="detailTabs"><button className={tab==='info'?'active':''} onClick={()=>setTab('info')}>Ma’lumot</button><button className={tab==='reviews'?'active':''} onClick={()=>setTab('reviews')}>Izohlar</button><button className={tab==='chat'?'active':''} onClick={()=>setTab('chat')}>Chat</button></div>
  {tab==='info'&&<><p>Sifatli va ishonchli mahsulot. O‘zbekiston bo‘ylab tezkor yetkazish va kafolat.</p><strong>{money(product.price)}</strong><small>Sotuvchi: {product.seller} · Omborda {product.stock} dona</small><button className="primary" onClick={()=>{addCart(product);close()}}>{copy[lang].add}</button><button className="catalog" onClick={()=>setTab('chat')}>Sotuvchiga yozish</button></>}
  {tab==='reviews'&&<div className="thread">{error&&<p role="alert" className="formError">{error}</p>}{reviews.map(r=><div className="review" key={r.id}><b>{r.user} ★★★★★</b><p>{r.text}</p></div>)}<form onSubmit={sendReview}><input required aria-label="Izoh matni" maxLength={2000} value={text} onChange={e=>setText(e.target.value)} placeholder="Izoh yozing..."/><button disabled={sending||!text.trim()}>Yuborish</button></form></div>}
  {tab==='chat'&&<ChatCenter user={user} compact target={{sellerId:product.sellerId,seller:product.seller,productId:product.id,productName:product.name}}/>}
  </div></div></div>
}
function PageTitle({title,back}){return <div className="pageTitle"><button onClick={back}>← Bosh sahifa</button><h1>{title}</h1></div>}
function Empty({title,text}){return <div className="emptyState"><i>◇</i><h2>{title}</h2><p>{text}</p></div>}

function CartPage({cart,setCart,user,go,notify}){const [checkout,setCheckout]=useState(false),[done,setDone]=useState(false),[error,setError]=useState(''),total=cart.reduce((s,p)=>s+p.price,0);const order=async e=>{e.preventDefault();setError('');const f=new FormData(e.currentTarget);try{await api('/orders',{method:'POST',body:JSON.stringify({userId:user.id,user:user.name,phone:f.get('phone'),address:f.get('address'),payment:f.get('payment'),total,items:cart.map(p=>({id:p.id,name:p.name,price:p.price,seller:p.seller}))})});setDone(true);notify('Buyurtma serverga yuborildi')}catch(err){setError(err.message)}};if(done)return <main className="subpage"><Empty title="Buyurtmangiz qabul qilindi!" text="Operator tez orada siz bilan bog‘lanadi."/ ><button className="primary center" onClick={()=>{setCart([]);go('home')}}>Bosh sahifaga</button></main>;return <main className="subpage"><PageTitle title={checkout?'Buyurtmani rasmiylashtirish':'Savatcha'} back={()=>checkout?setCheckout(false):go('home')}/>{checkout?<form className="checkout" onSubmit={order}><label>Ism<input required defaultValue={user.name}/></label><label>Telefon<input name="phone" type="tel" required defaultValue={user.phone||''} placeholder="+998 90 123 45 67"/></label><label>Manzil<textarea name="address" required placeholder="Shahar, ko‘cha va uy"/></label><label>To‘lov<select name="payment"><option>Yetkazilganda naqd</option><option>Uzcard / Humo</option><option>Visa / Mastercard</option></select></label><b>Jami: {money(total)}</b>{error&&<div className="formError">{error}</div>}<button className="primary full">Buyurtma berish</button></form>:cart.length?<div className="cartLayout"><section className="cartList">{cart.map((p,i)=><div className="cartItem" key={i}><ProductImage p={p}/><div><b>{p.name}</b><small>{p.category}</small></div><strong>{money(p.price)}</strong><button onClick={()=>setCart(cart.filter((_,x)=>x!==i))}>×</button></div>)}</section><aside className="summary"><h3>Buyurtma</h3><p>Mahsulotlar <b>{cart.length} ta</b></p><p>Yetkazish <b>Bepul</b></p><hr/><p className="sum">Jami <b>{money(total)}</b></p><button className="primary full" onClick={()=>setCheckout(true)}>Rasmiylashtirish →</button><button className="clearCart" onClick={()=>setCart([])}>Savatchani tozalash</button></aside></div>:<Empty title="Savatcha bo‘sh" text="Katalogdan mahsulot qo‘shing."/>}</main>}

function ProfilePage({user,go,onPanel,onLogout}){return <main className="subpage narrow"><PageTitle title="Mening profilim" back={()=>go('home')}/><section className="profilePage"><div className="avatar">{user.name[0]}</div><h2>{user.name}</h2><p>{user.email}</p><span className="roleTag">{user.role==='admin'?'Katta administrator':user.role==='seller'?'Sotuvchi':'Xaridor'}</span><div className="profileMenu"><button onClick={()=>go('chat')}>✉ Chatlarim <span>→</span></button>{user.role==='admin'&&<button onClick={()=>onPanel('users')}>Foydalanuvchilar va kirishlar <span>→</span></button>}<button onClick={onPanel}>▦ Shaxsiy kabinet <span>→</span></button><button onClick={()=>go('cart')}>🛒 Savatcham <span>→</span></button><button onClick={()=>go('favorites')}>♡ Sevimlilarim <span>→</span></button><button onClick={()=>go('seller')}>🏪 Sotuvchi bo‘lish <span>→</span></button></div><button className="logout" onClick={onLogout}>Hisobdan chiqish</button></section></main>}

function SellerApply({user,onPanel,notify}){const [status,setStatus]=useState(null),[error,setError]=useState('');useEffect(()=>{api('/seller-applications').then(a=>setStatus(a.find(x=>x.userId===user.id)?.status||null)).catch(()=>{})},[user.id]);if(user.role==='admin'||user.role==='seller'||status==='approved')return <main className="subpage narrow"><PageTitle title="Sotuvchi markazi" back={()=>history.back()}/><section className="applyBox"><i>🏪</i><h2>Sotuvchi kabinetingiz tayyor</h2><p>Mahsulot qo‘shish va buyurtmalarni boshqarishingiz mumkin.</p><button className="primary" onClick={onPanel}>Sotuvchi paneliga kirish</button></section></main>;if(status==='pending')return <main className="subpage narrow"><section className="applyBox"><i>⏳</i><h2>Arizangiz tekshirilmoqda</h2><p>Katta admin Ubaydulloh arizangizni ko‘rib chiqadi.</p></section></main>;const apply=async e=>{e.preventDefault();setError('');const f=new FormData(e.currentTarget);try{await api('/seller-applications',{method:'POST',body:JSON.stringify({userId:user.id,name:user.name,email:user.email,shop:f.get('shop'),phone:f.get('phone'),products:f.get('products')})});setStatus('pending');notify('Ariza backendga yuborildi')}catch(err){setError(err.message)}};return <main className="subpage narrow"><PageTitle title="Sotuvchi bo‘lish" back={()=>history.back()}/><form className="checkout" onSubmit={apply}><h2>Do‘kon ochish uchun ariza</h2><label>Do‘kon nomi<input name="shop" required placeholder="Masalan: Baraka Shop"/></label><label>Telefon<input name="phone" type="tel" required defaultValue={user.phone||''} placeholder="+998 90 123 45 67"/></label><label>Sotmoqchi bo‘lgan mahsulotlar<textarea name="products" required placeholder="Mahsulot turlarini yozing"/></label>{error&&<div className="formError">{error}</div>}<button className="primary full">Arizani yuborish</button></form></main>}
function InfoPage({type,go}){const help=type==='help';return <main className="subpage narrow"><PageTitle title={help?'Yordam markazi':'Bozorly haqida'} back={()=>go('home')}/>{help?<section className="faq">{[['Buyurtma qanday beriladi?','Mahsulotni savatchaga qo‘shib, rasmiylashtirish tugmasini bosing.'],['Yetkazish qancha vaqt?','Toshkent bo‘ylab 1–2, viloyatlarga 2–4 ish kuni.'],['Qaytarish mumkinmi?','Ha, 14 kun ichida qaytarish mumkin.'],['To‘lov turlari','Naqd, Uzcard, Humo, Visa va Mastercard.']].map(x=><details key={x[0]}><summary>{x[0]}</summary><p>{x[1]}</p></details>)}</section>:<section className="aboutPage"><img src="/products/home.png" alt="Bozorly"/><h2>Xarid va savdoni osonlashtiramiz</h2><p>Bozorly ishonchli sotuvchilar va xaridorlarni birlashtiradi. Sifatli mahsulot, xavfsiz buyurtma va tezkor yetkazib berish — bizning asosiy maqsadimiz.</p><div className="aboutStats"><b>1000+<small>mahsulot</small></b><b>500+<small>xaridor</small></b><b>24/7<small>yordam</small></b></div></section>}</main>}

function Dashboard({user,products,setProducts,onBack,onLogout,initialTab='overview'}){
 const role=user.role,[tab,setTab]=useState(initialTab),[applications,setApplications]=useState([]),[users,setUsers]=useState([]),[name,setName]=useState(''),[price,setPrice]=useState(''),[photo,setPhoto]=useState(''),[wallet,setWallet]=useState({balance:0,withdrawals:[]}),[orders,setOrders]=useState([]),[currentPassword,setCurrentPassword]=useState(''),[newPassword,setNewPassword]=useState(''),[confirmPassword,setConfirmPassword]=useState(''),[passwordMessage,setPasswordMessage]=useState(''),[passwordError,setPasswordError]=useState('')
 useEffect(()=>{if(role==='admin'){api('/seller-applications').then(setApplications).catch(()=>{});api('/users').then(setUsers).catch(()=>{})}api('/orders').then(setOrders).catch(()=>{});if(role!=='buyer')api('/wallet?seller='+encodeURIComponent(user.name)).then(setWallet).catch(()=>{})},[role,user.name])
 const nav=role==='admin'?[['overview','Umumiy'],['chat','Chatlar'],['sellers','Sotuvchilar'],['products','Mahsulotlar'],['orders','Buyurtmalar'],['users','Foydalanuvchilar'],['settings','Sozlamalar']]:role==='seller'?[['overview','Umumiy'],['chat','Chatlar'],['products','Mahsulotlarim'],['orders','Buyurtmalar'],['finance','Moliya'],['settings','Do‘kon sozlamalari']]:[['overview','Umumiy'],['chat','Chatlar'],['orders','Buyurtmalarim'],['favorites','Sevimlilar'],['addresses','Manzillar'],['seller','Sotuvchi bo‘lish']]
 const approve=async(a,ok)=>{try{const updated=await api('/seller-applications/'+a.id,{method:'PATCH',body:JSON.stringify({status:ok?'approved':'rejected'})});setApplications(applications.map(x=>x.id===a.id?updated:x))}catch(err){alert(err.message)}}
 const choosePhoto=e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>2500000){alert('Rasm hajmi 2.5 MB dan kichik bo‘lsin');e.target.value='';return}const reader=new FileReader();reader.onload=()=>setPhoto(reader.result);reader.readAsDataURL(file)}
 const add=e=>{e.preventDefault();if(!name||!price)return;const id=Date.now();setProducts([{...initialProducts[0],id,name,price:+price,seller:user.name,sellerId:user.id,image:photo||`https://loremflickr.com/600/480/product?lock=${id}`,fallback:fallback.Elektronika,custom:true},...products]);setName('');setPrice('');setPhoto('')}
 const changePassword=async e=>{e.preventDefault();setPasswordMessage('');setPasswordError('');if(newPassword!==confirmPassword){setPasswordError('Yangi parollar bir xil emas.');return}try{await api('/account/password',{method:'POST',body:JSON.stringify({currentPassword,newPassword})});setCurrentPassword('');setNewPassword('');setConfirmPassword('');setPasswordMessage('Parol muvaffaqiyatli almashtirildi.')}catch(err){setPasswordError(err.message)}}
 const withdraw=async()=>{const raw=prompt('Yechiladigan summa (so‘m):');if(!raw)return;try{const result=await api('/withdraw',{method:'POST',body:JSON.stringify({seller:user.name,amount:Number(raw)})});setWallet({...wallet,balance:result.balance,withdrawals:[...wallet.withdrawals,result]});alert('Demo yechish bajarildi. Pul hech qayerga yuborilmadi.')}catch(err){alert(err.message)}}
 return <div className="panel"><aside><button className="logoButton" onClick={onBack}><Logo light/></button><div className="profile"><i>{user.name[0]}</i><b>{user.name}</b><small>{role==='admin'?'Katta admin':role==='seller'?'Sotuvchi':'Xaridor'}</small></div><nav>{nav.map(x=><button className={tab===x[0]?'active':''} onClick={()=>setTab(x[0])} key={x[0]}>{x[1]}</button>)}</nav><button className="back" onClick={onBack}>← Do‘konga qaytish</button><button className="back danger" onClick={onLogout}>Chiqish</button></aside><main><div className="dashHead"><div><span>{role.toUpperCase()} PANEL</span><h1>{nav.find(x=>x[0]===tab)?.[1]}</h1><p>Xayrli kun, {user.name}!</p></div></div>{tab==='overview'&&<><div className="stats">{(role==='buyer'?[['🛒','Buyurtmalar','4'],['♡','Sevimlilar','12'],['🎁','Bonuslar','24 500'],['⭐','Daraja','Silver']]:[['💰','Jami savdo','24.8 mln'],['📦','Buyurtmalar','1,284'],['👥','Mijozlar','842'],['⭐','Reyting','4.9']]).map(x=><div key={x[1]}><i>{x[0]}</i><span>{x[1]}</span><b>{x[2]}</b><em>↗ faol</em></div>)}</div><section className="manage"><h2>So‘nggi faoliyat</h2><p>Hisobingiz faol. Barcha yangi ma’lumotlar shu bo‘limda ko‘rinadi.</p></section></>}
 {tab==='sellers'&&<section className="manage"><h2>Barcha do‘konlar va arizalar ({applications.length})</h2>{applications.length?applications.map(a=><div className="application" key={a.id}><div><b>🏪 {a.shop}</b><small>Egasi: {a.name} · {a.email} · {a.phone} · Tovarlar: {a.products}</small></div><span className={'status '+a.status}>{a.status==='approved'?'Faol do‘kon':a.status==='rejected'?'Rad etilgan':'Tekshiruvda'}</span>{a.status==='pending'&&<><button className="approve" onClick={()=>approve(a,true)}>Tasdiqlash</button><button className="reject" onClick={()=>approve(a,false)}>Rad etish</button></>}</div>):<Empty title="Hozircha do‘kon yo‘q" text="Sotuvchi arizalari shu yerda paydo bo‘ladi."/ >}</section>}
 {tab==='products'&&<section className="manage"><h2>{role==='admin'?'Barcha mahsulotlar':'Mening mahsulotlarim'}</h2><form className="add productAdd" onSubmit={add}><div className="uploadPhoto"><label>{photo?<img src={photo} alt="Tanlangan rasm"/>:<span>📷<small>Rasm tanlash</small></span>}<input type="file" accept="image/png,image/jpeg,image/webp" onChange={choosePhoto}/></label>{photo&&<button type="button" onClick={()=>setPhoto('')}>Rasmni olib tashlash</button>}</div><input value={name} onChange={e=>setName(e.target.value)} placeholder="Mahsulot nomi"/><input type="number" value={price} onChange={e=>setPrice(e.target.value)} placeholder="Narxi"/><button className="primary">Mahsulotni qo‘shish</button></form>{products.filter(p=>role==='admin'||p.seller===user.name).slice(0,15).map(p=><div className="row" key={p.id}><ProductImage p={p}/><div><b>{p.name}</b><small>{p.seller} · {p.stock} dona</small></div><strong>{money(p.price)}</strong><span>Sotuvda</span><button onClick={()=>setProducts(products.filter(x=>x.id!==p.id))}>O‘chirish</button></div>)}</section>}
 {tab==='orders'&&<section className="manage"><h2>{role==='buyer'?'Mening buyurtmalarim':'Sotilgan mahsulotlar'}</h2>{orders.filter(o=>role==='admin'||(role==='buyer'?String(o.userId)===String(user.id):o.items.some(i=>i.seller===user.name))).map(o=><div className="simpleRow" key={o.id}><div><b>#{o.id} · {o.user}</b><small>{o.items.filter(i=>role!=='seller'||i.seller===user.name).map(i=>i.name).join(', ')}</small></div><strong>{money(role==='seller'?o.items.filter(i=>i.seller===user.name).reduce((s,i)=>s+i.price,0):o.total)}</strong><span>{o.status}</span></div>)}</section>}
 {tab==='users'&&user.role==='admin'&&<AdminAccounts/>}
 {tab==='chat'&&<ChatCenter user={user}/>}

 {tab==='finance'&&<section className="manage"><h2>Moliya va demo hamyon</h2><div className="financeBig">{money(wallet.balance)} <small>mavjud balans</small></div><button className="primary" onClick={withdraw}>Pulni demo yechish</button><p className="demoWarning">Bu sinov funksiyasi: summa balansdan ayriladi, pul hech qanday karta yoki hisobga yuborilmaydi.</p>{wallet.withdrawals.map(w=><div className="simpleRow" key={w.id}><b>Yechildi: {money(w.amount)}</b><span>{w.status}</span></div>)}</section>}
 {tab==='addresses'&&<section className="manage settings"><h2>Yetkazib berish manzili</h2><label>Manzil<input placeholder="Toshkent, ko‘cha, uy"/></label><button className="primary" onClick={()=>alert('Manzil saqlandi')}>Saqlash</button></section>}
 {tab==='favorites'&&<section className="manage"><h2>Sevimlilar</h2><p>Sevimli mahsulotlaringiz do‘kondagi yurakcha bo‘limida saqlangan.</p></section>}
 {tab==='seller'&&<section className="manage"><h2>Sotuvchi bo‘lish</h2><p>Marketplace bosh sahifasidagi “Sotuvchi bo‘lish” bo‘limidan ariza yuboring. Katta admin arizani tasdiqlaydi.</p></section>}
 {tab==='settings'&&<section className="manage settings"><h2>Sozlamalar</h2><label>Nom<input defaultValue={user.name}/></label><label>Email<input defaultValue={user.email}/></label><button className="primary" onClick={()=>alert('Sozlamalar saqlandi')}>Saqlash</button><form className="passwordChange" onSubmit={changePassword}><h3>Parolni almashtirish</h3><label>Amaldagi parol<input required type="password" value={currentPassword} onChange={e=>setCurrentPassword(e.target.value)}/></label><label>Yangi parol<input required minLength="4" type="password" value={newPassword} onChange={e=>setNewPassword(e.target.value)}/></label><label>Yangi parolni tasdiqlang<input required minLength="4" type="password" value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)}/></label>{passwordError&&<div className="formError">{passwordError}</div>}{passwordMessage&&<p role="status">{passwordMessage}</p>}<button className="primary">Parolni almashtirish</button></form></section>}</main></div>
}

export default function App(){
 const [user,setUser]=useState(null),[checking,setChecking]=useState(true),[sessionError,setSessionError]=useState(''),[attempt,setAttempt]=useState(0)
 const [products,setProducts]=useState(()=>[...savedArray('bozor-custom-products'),...initialProducts])
 const [panel,setPanel]=useState(null),[lang,setLang]=useState(()=>{try{const value=localStorage.getItem('bozor-lang');return copy[value]?value:'uz'}catch{return 'uz'}})
 const userId=user?.id
 useEffect(()=>{try{localStorage.setItem('bozor-custom-products',JSON.stringify(products.filter(p=>p.custom)))}catch{setSessionError('Mahsulotni saqlash uchun xotira yetarli emas. Kichikroq rasm tanlang.')}},[products])
 useEffect(()=>{try{localStorage.setItem('bozor-lang',lang)}catch{/* Keep language in this session. */}document.documentElement.lang=lang},[lang])
 useEffect(()=>{
  let active=true
  api('/me').then(fresh=>{if(active){setUser(fresh);setSessionError('')}}).catch(err=>{if(active&&err.status!==401)setSessionError(err.message)}).finally(()=>{if(active)setChecking(false)})
  return ()=>{active=false}
 },[attempt])
 useEffect(()=>{
  if(!userId)return
  let active=true
  const refresh=()=>api('/me').then(fresh=>{if(active)setUser(fresh)}).catch(err=>{if(active&&err.status===401){setUser(null);setPanel(null)}})
  const expired=()=>{setUser(null);setPanel(null)}
  const interval=setInterval(refresh,10000)
  window.addEventListener('focus',refresh);window.addEventListener('bozor-session-expired',expired)
  return ()=>{active=false;clearInterval(interval);window.removeEventListener('focus',refresh);window.removeEventListener('bozor-session-expired',expired)}
 },[userId])
 const auth=u=>{setUser(u);setSessionError('');setPanel(null)}
 const logout=async()=>{try{await api('/logout',{method:'POST',body:'{}'});setUser(null);setPanel(null);setSessionError('')}catch(err){setSessionError(err.message)}}
 const openPanel=tab=>setPanel(typeof tab==='string'?tab:'overview')
 if(checking)return <main className="authSide"><p role="status">Hisob tekshirilmoqda…</p></main>
 if(sessionError&&!user)return <main className="authSide"><section className="authBox"><Logo/><p role="alert">{sessionError}</p><button className="primary" onClick={()=>{setChecking(true);setAttempt(value=>value+1)}}>Qayta ulanish</button></section></main>
 return <>{sessionError&&<div role="alert" className="formError">{sessionError}</div>}{!user?<AuthPage onAuth={auth}/>:panel?<Dashboard key={user.id+':'+user.role} {...{user,products,setProducts}} initialTab={panel} onBack={()=>setPanel(null)} onLogout={logout}/>:<Store key={user.id} {...{products,user,lang,setLang}} onLogout={logout} onPanel={openPanel}/>}</>
}
    
import {api} from './api.js'
import ChatCenter, {ChatShortcut} from './ChatCenter.jsx'
import AdminAccounts from './AdminAccounts.jsx'
