import {useCallback,useEffect,useRef,useState} from 'react'
import {api,subscribeRealtime} from './api.js'
import {localeFor,useI18n} from './i18n.jsx'
import './chat.css'

const same=(a,b)=>String(a)===String(b)
const partner=(conversation,user)=>same(conversation.sellerId,user.id)?conversation.buyerName:conversation.shopName||conversation.sellerName

export function ChatShortcut({onOpen,user}){
 const {t}=useI18n(),[count,setCount]=useState(0)
 useEffect(()=>{let active=true;const update=()=>api('/conversations').then(items=>{if(active)setCount(items.reduce((sum,item)=>sum+item.unreadCount,0))}).catch(()=>{});update();const unsubscribe=subscribeRealtime(update),interval=setInterval(update,20000);return()=>{active=false;unsubscribe();clearInterval(interval)}},[user.id])
 return <button className="chatShortcut" onClick={onOpen} aria-label={`${t('chats')}${count?`, ${count}`:''}`}><span aria-hidden="true">✉</span><small>{t('chats')}</small>{count>0&&<i>{count}</i>}</button>
}

export default function ChatCenter({user,target,compact=false}){
 const {t,lang}=useI18n(),[conversations,setConversations]=useState([]),[shops,setShops]=useState([]),[selected,setSelected]=useState(null),[query,setQuery]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true),[starting,setStarting]=useState(false),[retry,setRetry]=useState(0),[showShops,setShowShops]=useState(false),alive=useRef(true)
 const {sellerId,seller,productId,productName}=target||{}
 const clock=date=>date?new Date(date).toLocaleTimeString(localeFor(lang),{hour:'2-digit',minute:'2-digit'}):''
 const refresh=useCallback(async()=>{try{const items=await api('/conversations');if(alive.current){setConversations(items);setError('')}}catch(err){if(alive.current)setError(err.message)}finally{if(alive.current)setLoading(false)}},[])
 useEffect(()=>{alive.current=true;const initial=setTimeout(refresh,0),unsubscribe=subscribeRealtime(refresh),interval=setInterval(refresh,15000);window.addEventListener('focus',refresh);return()=>{alive.current=false;clearTimeout(initial);unsubscribe();clearInterval(interval);window.removeEventListener('focus',refresh)}},[refresh,user.id])
 useEffect(()=>{if(!showShops)return;let active=true;api('/shops').then(data=>{if(active)setShops(data)}).catch(err=>{if(active)setError(err.message)});return()=>{active=false}},[showShops])
 useEffect(()=>{if(!sellerId&&!seller)return;let active=true;const initial=setTimeout(()=>{setStarting(true);api('/conversations',{method:'POST',body:JSON.stringify({sellerId,seller,productId,productName})}).then(conversation=>{if(active){setSelected(conversation);setError('');refresh()}}).catch(err=>{if(active)setError(err.message)}).finally(()=>{if(active)setStarting(false)})},0);return()=>{active=false;clearTimeout(initial)}},[sellerId,seller,productId,productName,retry,refresh])
 const start=async shop=>{if(starting)return;setStarting(true);setError('');try{const conversation=await api('/conversations',{method:'POST',body:JSON.stringify({sellerId:shop.sellerId})});setSelected(conversation);setShowShops(false);await refresh()}catch(err){setError(err.message)}finally{setStarting(false)}}
 const visible=conversations.filter(item=>`${partner(item,user)} ${item.productName||''} ${item.lastMessage?.text||''}`.toLocaleLowerCase().includes(query.toLocaleLowerCase()))
 const current=conversations.find(item=>same(item.id,selected?.id))||selected
 return <section className={`messenger ${compact?'messengerCompact':''} ${current?'hasConversation':''}`} aria-label={t('conversations')}>
  {!compact&&<div className="conversationList"><div className="messengerHeading"><div><h2>{t('chats')}</h2><small>{t('online')}</small></div><button onClick={()=>setShowShops(value=>!value)} aria-label={showShops?t('backConversations'):t('newConversation')}>{showShops?'←':'+'}</button></div><label className="chatSearch"><span className="srOnly">{t('searchChats')}</span><span aria-hidden="true">⌕</span><input placeholder={t('searchChats')} value={query} onChange={e=>setQuery(e.target.value)}/></label>{loading&&<p className="chatNotice" role="status">{t('loadingChats')}</p>}{showShops?<div className="shopContacts"><p className="chatNotice">{t('selectStore')}</p>{shops.filter(shop=>!same(shop.sellerId,user.id)).map(shop=><button key={shop.sellerId} onClick={()=>start(shop)} disabled={starting}><span className="contactAvatar">{(shop.shop||shop.name||'?')[0]}</span><span className="contactText"><b>{shop.shop||shop.name}</b><small>{shop.sellerName}</small></span></button>)}</div>:<div className="conversationItems">{visible.map(item=><button key={item.id} className={same(item.id,current?.id)?'selectedConversation':''} onClick={()=>setSelected(item)}><span className="contactAvatar">{partner(item,user)?.[0]||'?'}</span><span className="contactText"><b>{partner(item,user)}</b><small>{item.lastMessage?.text||item.productName||t('startConversation')}</small></span><span className="contactMeta"><time>{clock(item.updatedAt)}</time>{item.unreadCount>0&&<em>{item.unreadCount}</em>}</span></button>)}{!loading&&!visible.length&&<p className="chatNotice">{query?t('noConversationFound'):t('noConversations')}</p>}</div>}</div>}
  <div className="conversationPane">{error&&<div className="chatError" role="alert">{error}<button onClick={()=>target?setRetry(value=>value+1):refresh()}>{t('retry')}</button></div>}{starting&&<p className="chatNotice" role="status">{t('openingChat')}</p>}{current?<Conversation key={current.id} conversation={current} user={user} onRead={refresh} onBack={()=>setSelected(null)}/>:!starting&&<div className="chatEmpty"><span aria-hidden="true">✉</span><h3>{t('messagesHere')}</h3><p>{compact?t('sellerUnavailable'):t('selectConversation')}</p></div>}</div>
 </section>
}

function Conversation({conversation,user,onRead,onBack}){
 const {t,lang}=useI18n(),[messages,setMessages]=useState([]),[draft,setDraft]=useState(''),[loading,setLoading]=useState(true),[sending,setSending]=useState(false),[error,setError]=useState(''),feed=useRef(null),alive=useRef(true),inFlight=useRef(false),endpoint=`/conversations/${encodeURIComponent(conversation.id)}`
 const clock=date=>date?new Date(date).toLocaleTimeString(localeFor(lang),{hour:'2-digit',minute:'2-digit'}):''
 const refresh=useCallback(async()=>{if(inFlight.current)return;inFlight.current=true;try{const items=await api(endpoint+'/messages');if(!alive.current)return;const unread=items.some(message=>!same(message.senderId,user.id)&&!message.readAt);if(unread&&document.visibilityState==='visible'){await api(endpoint+'/read',{method:'PATCH',body:'{}'});onRead()}if(alive.current){setMessages(previous=>[...items,...previous.filter(message=>message.pending)]);setError('')}}catch(err){if(alive.current)setError(err.message)}finally{inFlight.current=false;if(alive.current)setLoading(false)}},[endpoint,user.id,onRead])
 useEffect(()=>{alive.current=true;const initial=setTimeout(refresh,0),unsubscribe=subscribeRealtime(refresh),interval=setInterval(refresh,15000);return()=>{alive.current=false;clearTimeout(initial);unsubscribe();clearInterval(interval)}},[refresh])
 useEffect(()=>{feed.current?.scrollTo({top:feed.current.scrollHeight,behavior:loading?'auto':'smooth'})},[messages.length,loading])
 const send=async event=>{event.preventDefault();const text=draft.trim();if(!text||sending)return;const clientId=crypto.randomUUID(),optimistic={id:clientId,clientId,senderId:user.id,senderName:user.name,text,createdAt:new Date().toISOString(),pending:true};setDraft('');setMessages(previous=>[...previous,optimistic]);setSending(true);setError('');try{const message=await api(endpoint+'/messages',{method:'POST',body:JSON.stringify({text,clientId})});if(alive.current){setMessages(previous=>[...previous.filter(item=>item.id!==clientId&&item.id!==message.id),message].sort((a,b)=>String(a.createdAt||'').localeCompare(String(b.createdAt||''))));onRead()}}catch(err){if(alive.current){setMessages(previous=>previous.filter(item=>item.id!==clientId));setDraft(current=>current||text);setError(err.message)}}finally{if(alive.current)setSending(false)}}
 return <><div className="conversationHeading"><button className="chatBack" onClick={onBack} aria-label={t('backConversations')}>←</button><span className="contactAvatar">{partner(conversation,user)?.[0]}</span><div><h3>{partner(conversation,user)}</h3><small><i/> {t('online')}{conversation.productName?` · ${conversation.productName}`:''}</small></div><button className="chatRefresh" onClick={refresh} aria-label={t('refreshMessages')}>↻</button></div>{error&&<div className="chatError" role="alert">{error}</div>}<div className="messageFeed" ref={feed} role="log" aria-live="polite">{loading&&<p className="chatNotice" role="status">{t('loadingMessages')}</p>}{!loading&&!messages.length&&<p className="chatNotice firstMessage">{t('firstMessage')}</p>}{messages.map(message=><div className={`messageBubble ${same(message.senderId,user.id)?'ownMessage':''} ${message.pending?'pendingMessage':''}`} key={message.id}>{!same(message.senderId,user.id)&&<b>{message.senderName}</b>}<p>{message.text}</p><span><time dateTime={message.createdAt}>{clock(message.createdAt)}</time>{same(message.senderId,user.id)&&<small title={message.pending?t('waiting'):message.readAt?t('read'):t('sent')}>{message.pending?'◷':message.readAt?'✓✓':'✓'}</small>}</span></div>)}</div><form className="messageComposer" onSubmit={send}><button className="attachButton" type="button" disabled>＋</button><label><span className="srOnly">{t('messagePlaceholder')}</span><textarea rows={1} maxLength={4000} placeholder={t('messagePlaceholder')} value={draft} onChange={e=>setDraft(e.target.value)} onInput={e=>{e.currentTarget.style.height='auto';e.currentTarget.style.height=`${Math.min(e.currentTarget.scrollHeight,120)}px`}} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();e.currentTarget.form.requestSubmit()}}}/></label><button className="sendButton" disabled={sending||!draft.trim()} type="submit" aria-label={t('send')}>{sending?'…':'➤'}</button></form></>
}
